# https://github.com/travis-ci/travis-ci/issues/8836
sudo: required
addons:
  chrome: stable
language: dart
dart:
  - "2.0.0"
dart_task:
  - test: --platform vm
  - test: --platform chrome ./test/unorm_dart_test.dart
  - dartanalyzer: true
