name: unorm_dart
description: Unicode 8.0 Normalization - NFC, NFD, NFKC, NFKD.
  This is a Dart port of [walling/unorm](https://github.com/walling/unorm).
version: 0.2.0
homepage: https://github.com/yshrsmz/unorm-dart

environment:
  sdk: '<4.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.9.3
