name: unorm_dart
description: Unicode 8.0 Normalization - NFC, NFD, NFKC, NFKD.
  This is a Dart port of [walling/unorm](https://github.com/walling/unorm).
version: 0.1.2
homepage: https://github.com/yshrsmz/unorm-dart
author: Yasuhiro Shimizu <the.phantom.bane@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.5.1
